/*
 * Waiting List Api
 *
 * Ambulance Counseling Project API
 *
 * API version: 1.0.0
 * Contact: xkoricansky@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_counseling_wl

import (
	"github.com/gin-gonic/gin"
)

type AmbulanceCounselingAuthAPI interface {


    // UserLogin Post /ak-ambulance-counseling-api/login
    // User login 
     UserLogin(c *gin.Context)

    // UserRegister Post /ak-ambulance-counseling-api/register
    // User registration 
     UserRegister(c *gin.Context)

}