/*
 * Waiting List Api
 *
 * Ambulance Counseling Project API
 *
 * API version: 1.0.0
 * Contact: xkoricansky@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_counseling_wl

import (
	"github.com/gin-gonic/gin"
)

type AmbulanceCounselingAPI interface {


    // CreateQuestion Post /ak-ambulance-counseling-api/questions/new
    // Create a new question 
     CreateQuestion(c *gin.Context)

    // DeleteQuestionById Delete /ak-ambulance-counseling-api/delete/question/:id
    // Delete a question by ID 
     DeleteQuestionById(c *gin.Context)

    // DeleteReplyById Delete /ak-ambulance-counseling-api/delete/reply/:id
    // Delete a reply by ID 
     DeleteReplyById(c *gin.Context)

    // GetQuestionById Get /ak-ambulance-counseling-api/questions/:id
    // Get a specific question by ID 
     GetQuestionById(c *gin.Context)

    // GetQuestions Get /ak-ambulance-counseling-api/questions
    // Get all question summaries 
     GetQuestions(c *gin.Context)

    // GetRepliesByQuestionId Get /ak-ambulance-counseling-api/questions/:id/replies
    // Get all replies for a specific question 
     GetRepliesByQuestionId(c *gin.Context)

    // GetReplyById Get /ak-ambulance-counseling-api/questions/:id/reply/:replyId
    // Get a specific reply by ID 
     GetReplyById(c *gin.Context)

    // ReplyToQuestion Post /ak-ambulance-counseling-api/questions/:id/reply
    // Reply to a question 
     ReplyToQuestion(c *gin.Context)

    // UpdateQuestionById Put /ak-ambulance-counseling-api/update/question/:id
    // Update a question by ID 
     UpdateQuestionById(c *gin.Context)

    // UpdateReplyById Put /ak-ambulance-counseling-api/update/reply/:id
    // Update a reply by ID 
     UpdateReplyById(c *gin.Context)

}