/*
 * Waiting List Api
 *
 * Ambulance Counseling Project API
 *
 * API version: 1.0.0
 * Contact: xkoricansky@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_counseling_wl

type User struct {

	// Unique identifier for the user
	Id string `json:"id"`

	// Name of the user
	Name string `json:"name"`

	// Email address of the user
	Email string `json:"email"`

	// Type of user (patient, doctor)
	Type string `json:"type"`
}
