/*
 * Waiting List Api
 *
 * Ambulance Counseling Project API
 *
 * API version: 1.0.0
 * Contact: xkoricansky@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_counseling_wl

type RegistrationForm struct {

	// Name of the user
	Name string `json:"name"`

	// Email address of the user
	Email string `json:"email"`

	// Password for the user account
	Password string `json:"password"`
}
