/*
 * Waiting List Api
 *
 * Ambulance Counseling Project API
 *
 * API version: 1.0.0
 * Contact: xkoricansky@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_counseling_wl

import (
	"time"
)

type Reply struct {

	// Unique identifier for the reply
	Id string `json:"id"`

	// Unique identifier for the user who made the reply
	UserId string `json:"userId"`

	// The text of the reply
	Text string `json:"text"`

	// Timestamp when the reply was created
	CreatedAt time.Time `json:"createdAt"`

	// Indicates if there is another reply to the question, if true reply cannot be edited or deleted
	RepliedTo bool `json:"repliedTo"`

	// If the reply is from a doctor, this field contains the doctor's name
	DoctorName string `json:"doctorName,omitempty"`
}
