/*
 * Waiting List Api
 *
 * Ambulance Counseling Project API
 *
 * API version: 1.0.0
 * Contact: xkoricansky@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_counseling_wl

import (
	"time"
)

type Question struct {

	// Unique identifier for the question
	Id string `json:"id"`

	// Unique identifier for the patient who submitted the question
	PatientId string `json:"patientId"`

	// A brief summary of the question
	Summary string `json:"summary"`

	// The question text submitted by the patient
	Question string `json:"question"`

	// List of replies to the question if any
	Replies []Reply `json:"replies,omitempty"`

	// Timestamp when the question was created
	CreatedAt time.Time `json:"createdAt"`

	// Timestamp when the question was last updated
	LastUpdated time.Time `json:"lastUpdated"`

	// Indicates if the question has been replied to, if true question cannot be edited
	RepliedTo bool `json:"repliedTo"`
}
