/*
 * Waiting List Api
 *
 * Ambulance Counseling Project API
 *
 * API version: 1.0.0
 * Contact: xkoricansky@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_counseling_wl

type User struct {

	// Unique identifier for the user
	Id string `json:"id" bson:"id"`

	// Name of the user
	Name string `json:"name" bson:"name"`

	// Email address of the user
	Email string `json:"email" bson:"email"`

	// Type of user (patient, doctor)
	Type string `json:"type" bson:"type"`

	// Hashed password - not exposed in JSON responses
	PasswordHash string `json:"-" bson:"passwordHash"`
}
